### ISSUE TITLE
useStore batching is broken

### ISSUE THREAD

**Issue by artalar** [ai/nanostores#24]
Hi! This is wrong batching implementation https://github.com/ai/nanostores/blob/main/react/index.js#L22
Specially for the React...

[Here the reproduce](https://codesandbox.io/s/nanostores-rerenders-example-882p9).

You should use [unstable_batchedUpdates](unstable_batchedUpdates) and probably https://github.com/facebook/react/tree/master/packages/use-subscription

**Comment by ai** [comment]
@artalar I do not see any error in bug reproduction.

Is it about performance and not about the bug?

Is it related to https://github.com/ai/nanostores/issues/16?

**Comment by ai** [comment]
I moved to more standard batching until React 18 release https://github.com/ai/nanostores/commit/142b4ca5eb7a1214b8a4cf6629af33e9bb2e4062
