### ISSUE TITLE
publish docs

### ISSUE THREAD

**Issue by Guria** [ai/nanostores#27]
As for now logux.io were updated not to have @logux/state references this project doesn't have web site with own documentation.
Do we expect to have such or readme is enough as for now?

**Comment by euaaaio** [comment]
Readme is enough, but we need to extend it a little bit over time.

**Comment by Guria** [comment]
Lets also note that logux.io site tries to link some parts to this repo for some types

**Comment by ai** [comment]
@Guria give me links, I will fix them

**Comment by Guria** [comment]
Example:

> Returns SyncMapBuilder.

https://logux.io/web-api/#globals-definesyncmap

**Comment by ai** [comment]
@Guria `SyncMapBuilder` is a type from `@logux/client`, not Nano Stores

**Comment by ai** [comment]
> Do we expect to have such or readme is enough as for now?

Yeap. I think we do not need special API page, since the project is very simple.

**Comment by Guria** [comment]
Sorry, seems I sed wrong example.
Here one that links to nanostores:
![Uploading image.png…]()

**Comment by ai** [comment]
It is OK. We had the same links to Nano Events and Redux types.
